# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: ip/spi/spi.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi || ORIG_REF_NAME==spi} -quiet] -quiet

# XDC: c:/CodeRepos/mSDFDFT/FPGA_VIVADO/FPGA_VIVADO.gen/sources_1/ip/spi/spi_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi || ORIG_REF_NAME==spi} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/CodeRepos/mSDFDFT/FPGA_VIVADO/FPGA_VIVADO.gen/sources_1/ip/spi/spi.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi || ORIG_REF_NAME==spi} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/CodeRepos/mSDFDFT/FPGA_VIVADO/FPGA_VIVADO.gen/sources_1/ip/spi/spi_ooc.xdc

# XDC: c:/CodeRepos/mSDFDFT/FPGA_VIVADO/FPGA_VIVADO.gen/sources_1/ip/spi/spi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi || ORIG_REF_NAME==spi} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
